environment:
  matrix:
  - julia_version: 0.6
#  - julia_version: 0.7
#  - julia_version: latest

platform:
  - x86
  - x64

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia_version: latest

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/simonbyrne/Appveyor.jl/master/bin/install.ps1'))

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - julia -e "Pkg.clone(pwd(), \"Appveyor\"); Pkg.build(\"Appveyor\")"

test_script:
  - julia -e "Pkg.test(\"Appveyor\")"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))